// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs72kQQRdvI31F5l8PQ7WcE_o-5RL3eeI',
    appId: '1:1083678557109:web:57488ef77b0ce8bd0a4ffc',
    messagingSenderId: '1083678557109',
    projectId: 'propertypulse-136d6',
    authDomain: 'propertypulse-136d6.firebaseapp.com',
    storageBucket: 'propertypulse-136d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvnwSydPAtTyTtonEbiXiGa8J3_-5WqU',
    appId: '1:1083678557109:android:cdac6ddaf14404260a4ffc',
    messagingSenderId: '1083678557109',
    projectId: 'propertypulse-136d6',
    storageBucket: 'propertypulse-136d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM37NTT1hL9Wtc9lnvm3uYL4cqHGmFsjk',
    appId: '1:1083678557109:ios:4687855b24ca6a2d0a4ffc',
    messagingSenderId: '1083678557109',
    projectId: 'propertypulse-136d6',
    storageBucket: 'propertypulse-136d6.firebasestorage.app',
    iosBundleId: 'com.example.propertyPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM37NTT1hL9Wtc9lnvm3uYL4cqHGmFsjk',
    appId: '1:1083678557109:ios:4687855b24ca6a2d0a4ffc',
    messagingSenderId: '1083678557109',
    projectId: 'propertypulse-136d6',
    storageBucket: 'propertypulse-136d6.firebasestorage.app',
    iosBundleId: 'com.example.propertyPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs72kQQRdvI31F5l8PQ7WcE_o-5RL3eeI',
    appId: '1:1083678557109:web:df83865c861c0c3f0a4ffc',
    messagingSenderId: '1083678557109',
    projectId: 'propertypulse-136d6',
    authDomain: 'propertypulse-136d6.firebaseapp.com',
    storageBucket: 'propertypulse-136d6.firebasestorage.app',
  );
}
